In [1]:
import main
from importlib import reload

In [2]:
cool_file = '/media/lchumpitaz/New Volume/work/programas/Data/Hi-C/mcools/GM12878_inSitu_MboI.hg19.mapq_30.1000.mcool'

In [3]:
track = main.get_track(cool_file)

In [4]:
track

,chrom,start,end,weight,gene_count,E1_clip,E2_clip,E3_clip,E1_log,E2_log,E3_log,E1_cliplog,E2_cliplog,E3_cliplog,E1_tanh,E2_tanh,E3_tanh,E1_tanhlog,E2_tanhlog,E3_tanhlog
0,chr1,0,100000,NaN,0.22742,-0.007171,0.042143,-0.009594,0.006795,-0.088022,-0.106837,0.009986,-0.087326,-0.105729,-0.000932,-0.049705,-0.002799,0.001024,-0.062647,-0.090092
1,chr1,100000,200000,NaN,0.42396,-0.005657,0.041664,-0.012397,0.008801,-0.087031,-0.105676,0.011560,-0.086684,-0.104810,0.000003,-0.049418,-0.004627,0.002111,-0.062292,-0.088788
2,chr1,200000,300000,NaN,1.00000,-0.006490,0.045712,-0.010055,0.009414,-0.091212,-0.107901,0.011489,-0.089520,-0.107189,-0.000266,-0.052002,-0.002672,0.001900,-0.065035,-0.090863
3,chr1,300000,400000,NaN,0.46231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,chr1,400000,500000,NaN,0.07159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28818,chr22,50900000,51000000,0.001843,0.65086,-0.053043,0.070371,0.080572,0.057051,0.044749,0.101073,0.058385,0.048054,-0.090654,0.057857,0.061135,0.065299,0.058677,0.053448,-0.076626
28819,chr22,51000000,51100000,0.001847,0.40762,-0.069230,0.054063,0.095038,0.068796,0.021322,0.108589,0.069312,0.026265,-0.090785,0.070820,0.040859,0.049328,0.069925,0.032497,-0.061877
28820,chr22,51100000,51200000,0.002423,0.74186,-0.096245,0.037962,0.098224,0.086949,-0.007810,0.107059,0.086057,0.001538,-0.072693,0.084472,0.014003,0.026598,0.083051,0.007678,-0.031230
28821,chr22,51200000,51300000,NaN,0.40099,-0.069493,0.048140,0.081499,0.060528,0.018372,0.044210,0.057297,0.022175,-0.035669,0.057527,0.022204,0.010402,0.056953,0.019376,-0.014794
28822,chr22,51300000,51304566,NaN,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
cool_dir = '/media/lchumpitaz/New Volume/work/programas/Data/Hi-C'
n = 3

In [14]:
df, tracks = main.multi_track(cool_dir, n=3)

Analyzing GM12878
Analyzing HMEC
Analyzing HUVEC
Analyzing IMR90
Analyzing K562
Analyzing KBM7
Analyzing NHEK

In [15]:
df

,cell_line,assembly,path,cooler
0,GM12878,hg19,/media/lchumpitaz/New Volume/work/programas/Da...,"<Cooler ""GM12878_inSitu_MboI.hg19.mapq_30.1000..."
1,HMEC,hg19,/media/lchumpitaz/New Volume/work/programas/Da...,"<Cooler ""HMEC_inSitu_MboI.hg19.mapq_30.1000.mc..."
2,HUVEC,hg19,/media/lchumpitaz/New Volume/work/programas/Da...,"<Cooler ""HUVEC_inSitu_MboI.hg19.mapq_30.1000.m..."
3,IMR90,hg19,/media/lchumpitaz/New Volume/work/programas/Da...,"<Cooler ""IMR90_inSitu_MboI.hg19.mapq_30.1000.m..."
4,K562,hg19,/media/lchumpitaz/New Volume/work/programas/Da...,"<Cooler ""K562_inSitu_MboI.hg19.mapq_30.1000.mc..."
5,KBM7,hg19,/media/lchumpitaz/New Volume/work/programas/Da...,"<Cooler ""KBM7_inSitu_MboI.hg19.mapq_30.1000.mc..."
6,NHEK,hg19,/media/lchumpitaz/New Volume/work/programas/Da...,"<Cooler ""NHEK_inSitu_MboI.hg19.mapq_30.1000.mc..."

In [35]:
tracks[0]

,chrom,start,end,weight,gene_count,E1_clip,E2_clip,E3_clip,E1_log,E2_log,E3_log,E1_cliplog,E2_cliplog,E3_cliplog,E1_tanh,E2_tanh,E3_tanh,E1_tanhlog,E2_tanhlog,E3_tanhlog
0,chr1,0,100000,NaN,0.22742,-0.007171,0.042143,-0.009594,0.006795,-0.088022,-0.106837,0.009986,-0.087326,-0.105729,-0.000932,-0.049705,-0.002799,0.001024,-0.062647,-0.090092
1,chr1,100000,200000,NaN,0.42396,-0.005657,0.041664,-0.012397,0.008801,-0.087031,-0.105676,0.011560,-0.086684,-0.104810,0.000003,-0.049418,-0.004627,0.002111,-0.062292,-0.088788
2,chr1,200000,300000,NaN,1.00000,-0.006490,0.045712,-0.010055,0.009414,-0.091212,-0.107901,0.011489,-0.089520,-0.107189,-0.000266,-0.052002,-0.002672,0.001900,-0.065035,-0.090863
3,chr1,300000,400000,NaN,0.46231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,chr1,400000,500000,NaN,0.07159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28818,chr22,50900000,51000000,0.001843,0.65086,-0.053043,0.070371,0.080572,0.057051,0.044749,0.101073,0.058385,0.048054,-0.090654,0.057857,0.061135,0.065299,0.058677,0.053448,-0.076626
28819,chr22,51000000,51100000,0.001847,0.40762,-0.069230,0.054063,0.095038,0.068796,0.021322,0.108589,0.069312,0.026265,-0.090785,0.070820,0.040859,0.049328,0.069925,0.032497,-0.061877
28820,chr22,51100000,51200000,0.002423,0.74186,-0.096245,0.037962,0.098224,0.086949,-0.007810,0.107059,0.086057,0.001538,-0.072693,0.084472,0.014003,0.026598,0.083051,0.007678,-0.031230
28821,chr22,51200000,51300000,NaN,0.40099,-0.069493,0.048140,0.081499,0.060528,0.018372,0.044210,0.057297,0.022175,-0.035669,0.057527,0.022204,0.010402,0.056953,0.019376,-0.014794
28822,chr22,51300000,51304566,NaN,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
def multi_analyze(df, tracks, n):
    #chroms = tracks[0].chrom.unique()
    Es = tracks[0].columns.tolist()[5::n]
    results = list()
    for E in Es:
        compared_df = tracks[0].iloc[:, :5]
        for i in range(len(df)):
            cell_line = df.iloc[i].cell_line
            compared_df[cell_line] = tracks[i][E]
        results.append(compared_df)
    return results

In [45]:
Es = tracks[0].columns.tolist()[5::n]

In [56]:
tracks[0][Es[0]]

0       -0.007171
1       -0.005657
2       -0.006490
3             NaN
4             NaN
           ...
28818   -0.053043
28819   -0.069230
28820   -0.096245
28821   -0.069493
28822         NaN
Name: E1_clip, Length: 28823, dtype: float64

In [34]:
chroms[0]

'chr1'